/**
 * Familiar answer words for the daily game. Kannada meanings are original Sirigannada copy,
 * released under CC BY-SA 4.0. English explanations below are original counterparts.
 */
export const WORD_GAME_ANSWERS = [
  { word: "ಹೂವು", meaningKn: "ಸಸ್ಯದಲ್ಲಿ ಅರಳುವ ಬಣ್ಣದ ಮತ್ತು ಸುಗಂಧದ ಭಾಗ." },
  { word: "ಪುಸ್ತಕ", meaningKn: "ಓದಲು ಪುಟಗಳನ್ನು ಸೇರಿಸಿ ಮಾಡಿದ ಕೃತಿ." },
  { word: "ಸೂರ್ಯ", meaningKn: "ಭೂಮಿಗೆ ಬೆಳಕು ಮತ್ತು ಬಿಸಿಲು ಕೊಡುವ ನಕ್ಷತ್ರ." },
  { word: "ಚಂದ್ರ", meaningKn: "ರಾತ್ರಿ ಆಕಾಶದಲ್ಲಿ ಕಾಣುವ ಭೂಮಿಯ ಉಪಗ್ರಹ." },
  { word: "ನಕ್ಷತ್ರ", meaningKn: "ರಾತ್ರಿ ಆಕಾಶದಲ್ಲಿ ಹೊಳೆಯುವ ದೂರದ ಆಕಾಶಕಾಯ." },
  { word: "ಆಕಾಶ", meaningKn: "ನಮ್ಮ ಮೇಲೆ ಕಾಣುವ ವಿಶಾಲವಾದ ಬಯಲು." },
  { word: "ಮಳೆ", meaningKn: "ಮೋಡಗಳಿಂದ ಹನಿಗಳಾಗಿ ಬೀಳುವ ನೀರು." },
  { word: "ಗಾಳಿ", meaningKn: "ನಮ್ಮ ಸುತ್ತಲೂ ಇರುವ, ಉಸಿರಾಡಲು ಬೇಕಾದ ವಾಯು." },
  { word: "ಬೆಂಕಿ", meaningKn: "ಉರಿಯುವಾಗ ಬೆಳಕು ಮತ್ತು ಬಿಸಿ ಕೊಡುವ ಜ್ವಾಲೆ." },
  { word: "ಸಮುದ್ರ", meaningKn: "ಉಪ್ಪುನೀರಿನಿಂದ ತುಂಬಿರುವ ಬಹಳ ದೊಡ್ಡ ಜಲರಾಶಿ." },
  { word: "ನದಿ", meaningKn: "ಒಂದು ದಿಕ್ಕಿನಲ್ಲಿ ಹರಿಯುವ ನೈಸರ್ಗಿಕ ನೀರಿನ ದಾರಿ." },
  { word: "ಬೆಟ್ಟ", meaningKn: "ಸುತ್ತಲಿನ ನೆಲಕ್ಕಿಂತ ಎತ್ತರವಾಗಿರುವ ಭೂಭಾಗ." },
  { word: "ಮರ", meaningKn: "ಕಾಂಡ, ಕೊಂಬೆ ಮತ್ತು ಎಲೆಗಳಿರುವ ದೊಡ್ಡ ಸಸ್ಯ." },
  { word: "ಗಿಡ", meaningKn: "ಮರಕ್ಕಿಂತ ಚಿಕ್ಕದಾಗಿ ಬೆಳೆಯುವ ಸಸ್ಯ." },
  { word: "ಹಣ್ಣು", meaningKn: "ಹೂವಿನ ಬಳಿಕ ಸಸ್ಯದಲ್ಲಿ ಬೆಳೆದು ಸಾಮಾನ್ಯವಾಗಿ ತಿನ್ನುವ ಭಾಗ." },
  { word: "ತರಕಾರಿ", meaningKn: "ಅಡುಗೆಯಲ್ಲಿ ಬಳಸುವ ಸಸ್ಯದ ತಿನ್ನಬಹುದಾದ ಭಾಗ." },
  { word: "ಬೆಳ್ಳುಳ್ಳಿ", meaningKn: "ಅಡುಗೆಗೆ ರುಚಿ ಮತ್ತು ವಾಸನೆ ಕೊಡುವ ಬಿಳಿ ಗೆಡ್ಡೆ." },
  { word: "ಈರುಳ್ಳಿ", meaningKn: "ಪದರಗಳಿರುವ, ಅಡುಗೆಯಲ್ಲಿ ಬಳಸುವ ಒಂದು ಗೆಡ್ಡೆ." },
  { word: "ನಾಯಿ", meaningKn: "ಮನುಷ್ಯರ ಜೊತೆ ಸಾಕುವ ಪರಿಚಿತ ಪ್ರಾಣಿ." },
  { word: "ಬೆಕ್ಕು", meaningKn: "ಮೃದುವಾದ ಕೂದಲಿರುವ, ಮನೆಗಳಲ್ಲಿ ಸಾಕುವ ಚಿಕ್ಕ ಪ್ರಾಣಿ." },
  { word: "ಆಕಳು", meaningKn: "ಹಾಲಿಗಾಗಿ ಸಾಕುವ ದೊಡ್ಡ ಸಾಕುಪ್ರಾಣಿ." },
  { word: "ಕುದುರೆ", meaningKn: "ಓಡಲು ಮತ್ತು ಸವಾರಿ ಮಾಡಲು ಬಳಸುವ ಪ್ರಾಣಿ." },
  { word: "ಹಕ್ಕಿ", meaningKn: "ರೆಕ್ಕೆ ಮತ್ತು ಗರಿಗಳಿರುವ, ಸಾಮಾನ್ಯವಾಗಿ ಹಾರುವ ಜೀವಿ." },
  { word: "ಹಾವು", meaningKn: "ಕಾಲುಗಳಿಲ್ಲದೆ ನೆಲದ ಮೇಲೆ ಹರಿಯುವ ಉದ್ದ ಜೀವಿ." },
  { word: "ಇಲಿ", meaningKn: "ಉದ್ದ ಬಾಲವಿರುವ ಚಿಕ್ಕ ಪ್ರಾಣಿ." },
  { word: "ಮೊಟ್ಟೆ", meaningKn: "ಹಕ್ಕಿ ಮೊದಲಾದ ಜೀವಿಗಳ ಮರಿ ಬೆಳೆಯುವ ಕವಚದ ವಸ್ತು." },
  { word: "ಬಾಗಿಲು", meaningKn: "ಒಳಗೆ ಹೋಗಲು ಮತ್ತು ಹೊರಗೆ ಬರಲು ತೆರೆಯುವ ಭಾಗ." },
  { word: "ಕಿಟಕಿ", meaningKn: "ಗಾಳಿ ಮತ್ತು ಬೆಳಕು ಬರಲು ಗೋಡೆಯಲ್ಲಿ ಮಾಡಿದ ತೆರವು." },
  { word: "ಕುರ್ಚಿ", meaningKn: "ಒಬ್ಬರು ಕುಳಿತುಕೊಳ್ಳಲು ಬಳಸುವ ಆಸನ." },
  { word: "ಮೇಜು", meaningKn: "ವಸ್ತುಗಳನ್ನು ಇಡಲು ಕಾಲುಗಳಿರುವ ಸಮತಟ್ಟಾದ ಪೀಠೋಪಕರಣ." },
  { word: "ದೀಪ", meaningKn: "ಕತ್ತಲಿನಲ್ಲಿ ಬೆಳಕು ಕೊಡುವ ಸಾಧನ." },
  { word: "ಕನ್ನಡಿ", meaningKn: "ನಮ್ಮ ಪ್ರತಿಬಿಂಬವನ್ನು ತೋರಿಸುವ ನಯವಾದ ವಸ್ತು." },
  { word: "ಗಡಿಯಾರ", meaningKn: "ಸಮಯವನ್ನು ತೋರಿಸುವ ಸಾಧನ." },
  { word: "ಬಟ್ಟೆ", meaningKn: "ಧರಿಸಲು ಅಥವಾ ಹೊಲಿಯಲು ಬಳಸುವ ನೆಯ್ದ ವಸ್ತು." },
  { word: "ಕಾಗದ", meaningKn: "ಬರೆಯಲು, ಮುದ್ರಿಸಲು ಅಥವಾ ಚಿತ್ರ ಬಿಡಿಸಲು ಬಳಸುವ ಹಾಳೆ." },
  { word: "ಬಣ್ಣ", meaningKn: "ವಸ್ತು ಕಣ್ಣಿಗೆ ಕಾಣುವ ಕೆಂಪು, ನೀಲಿ ಮೊದಲಾದ ಗುಣ." },
  { word: "ಚಿತ್ರ", meaningKn: "ಬಿಡಿಸಿದ ಅಥವಾ ತೆಗೆದ ದೃಶ್ಯದ ರೂಪ." },
  { word: "ಊಟ", meaningKn: "ತಿನ್ನುವ ಆಹಾರ ಅಥವಾ ಆಹಾರ ತಿನ್ನುವ ಕ್ರಿಯೆ." },
  { word: "ಅನ್ನ", meaningKn: "ಬೇಯಿಸಿದ ಅಕ್ಕಿಯಿಂದ ಮಾಡುವ ಮುಖ್ಯ ಆಹಾರ." },
  { word: "ರೊಟ್ಟಿ", meaningKn: "ಹಿಟ್ಟನ್ನು ತಟ್ಟಿ ಬೇಯಿಸಿ ಮಾಡುವ ಆಹಾರ." },
  { word: "ಹಣ", meaningKn: "ವಸ್ತು ಅಥವಾ ಸೇವೆಯನ್ನು ಕೊಳ್ಳಲು ಬಳಸುವ ಮಾಧ್ಯಮ." },
  { word: "ಅಂಗಡಿ", meaningKn: "ವಸ್ತುಗಳನ್ನು ಮಾರುವ ಸ್ಥಳ." },
  { word: "ರಸ್ತೆ", meaningKn: "ಜನರು ಮತ್ತು ವಾಹನಗಳು ಸಂಚರಿಸುವ ದಾರಿ." },
  { word: "ಬಸ್ಸು", meaningKn: "ಹಲವು ಜನರನ್ನು ಕರೆದೊಯ್ಯುವ ದೊಡ್ಡ ರಸ್ತೆ ವಾಹನ." },
  { word: "ರೈಲು", meaningKn: "ಹಳಿಗಳ ಮೇಲೆ ಓಡುವ ಹಲವು ಬೋಗಿಗಳ ವಾಹನ." },
  { word: "ಆಸ್ಪತ್ರೆ", meaningKn: "ಅನಾರೋಗ್ಯಕ್ಕೆ ಚಿಕಿತ್ಸೆ ನೀಡುವ ಸ್ಥಳ." },
  { word: "ಔಷಧ", meaningKn: "ರೋಗವನ್ನು ತಡೆಯಲು ಅಥವಾ ಗುಣಪಡಿಸಲು ಬಳಸುವ ಮದ್ದು." },
  { word: "ಶಾಲೆ", meaningKn: "ವಿದ್ಯಾರ್ಥಿಗಳು ಕಲಿಯಲು ಹೋಗುವ ಸ್ಥಳ." },
  { word: "ಶಿಕ್ಷಕ", meaningKn: "ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಪಾಠ ಹೇಳಿಕೊಡುವ ವ್ಯಕ್ತಿ." },
  { word: "ವಿದ್ಯಾರ್ಥಿ", meaningKn: "ಶಾಲೆ ಅಥವಾ ಬೇರೆ ಸ್ಥಳದಲ್ಲಿ ಕಲಿಯುವ ವ್ಯಕ್ತಿ." },
  { word: "ಅಪ್ಪ", meaningKn: "ತಂದೆಯನ್ನು ಕರೆಯುವ ಪರಿಚಿತ ಪದ." },
  { word: "ಅಮ್ಮ", meaningKn: "ತಾಯಿಯನ್ನು ಕರೆಯುವ ಪರಿಚಿತ ಪದ." },
  { word: "ಅಕ್ಕ", meaningKn: "ತನ್ನಿಗಿಂತ ಹಿರಿಯಳಾದ ಸಹೋದರಿ." },
  { word: "ಅಣ್ಣ", meaningKn: "ತನ್ನಿಗಿಂತ ಹಿರಿಯನಾದ ಸಹೋದರ." },
  { word: "ತಂಗಿ", meaningKn: "ತನ್ನಿಗಿಂತ ಕಿರಿಯಳಾದ ಸಹೋದರಿ." },
  { word: "ತಮ್ಮ", meaningKn: "ತನ್ನಿಗಿಂತ ಕಿರಿಯನಾದ ಸಹೋದರ." },
  { word: "ಮಗು", meaningKn: "ಚಿಕ್ಕ ವಯಸ್ಸಿನ ಬಾಲಕ ಅಥವಾ ಬಾಲಕಿ." },
  { word: "ಗೆಳೆಯ", meaningKn: "ಪ್ರೀತಿ ಮತ್ತು ನಂಬಿಕೆಯಿಂದ ಜೊತೆಗಿರುವ ಸ್ನೇಹಿತ." },
  { word: "ಹೆಸರು", meaningKn: "ವ್ಯಕ್ತಿ, ಸ್ಥಳ ಅಥವಾ ವಸ್ತುವನ್ನು ಗುರುತಿಸುವ ಪದ." },
  { word: "ದೇಶ", meaningKn: "ತನ್ನದೇ ಆಡಳಿತ ಮತ್ತು ಗಡಿಗಳಿರುವ ಭೂಪ್ರದೇಶ." },
  { word: "ರಾತ್ರಿ", meaningKn: "ಸೂರ್ಯ ಮುಳುಗಿದ ಬಳಿಕದ ಕತ್ತಲಿನ ಸಮಯ." },
  { word: "ದಿನ", meaningKn: "ಬೆಳಗಿನಿಂದ ರಾತ್ರಿವರೆಗಿನ ಕಾಲ ಅಥವಾ ಇಪ್ಪತ್ತನಾಲ್ಕು ಗಂಟೆ." },
  { word: "ವಾರ", meaningKn: "ಏಳು ದಿನಗಳ ಕಾಲಮಾನ." },
  { word: "ತಿಂಗಳು", meaningKn: "ವರ್ಷವನ್ನು ಹನ್ನೆರಡು ಭಾಗಗಳಾಗಿ ಹಂಚಿದ ಒಂದು ಕಾಲಮಾನ." },
  { word: "ವರ್ಷ", meaningKn: "ಹನ್ನೆರಡು ತಿಂಗಳುಗಳ ಕಾಲಮಾನ." },
  { word: "ಸಮಯ", meaningKn: "ಘಟನೆ ನಡೆಯುವ ಅಥವಾ ಕೆಲಸ ಮಾಡುವ ಕಾಲ." },
  { word: "ಹಬ್ಬ", meaningKn: "ಸಂತೋಷದಿಂದ ಆಚರಿಸುವ ವಿಶೇಷ ದಿನ." },
  { word: "ಆಟ", meaningKn: "ಸಂತೋಷ, ವ್ಯಾಯಾಮ ಅಥವಾ ಸ್ಪರ್ಧೆಗಾಗಿ ಆಡುವ ಚಟುವಟಿಕೆ." },
  { word: "ಕೆಲಸ", meaningKn: "ಮಾಡಬೇಕಾದ ಕಾರ್ಯ ಅಥವಾ ಉದ್ಯೋಗ." },
  { word: "ಸಂಗೀತ", meaningKn: "ಸ್ವರ ಮತ್ತು ಲಯಗಳನ್ನು ಹೊಂದಿಸಿದ ಕಲೆ." },
  { word: "ಹಾಡು", meaningKn: "ರಾಗ ಮತ್ತು ಲಯದೊಂದಿಗೆ ಹಾಡುವ ಪದಗಳ ರಚನೆ." },
  { word: "ಕಥೆ", meaningKn: "ಘಟನೆಗಳನ್ನು ಕ್ರಮವಾಗಿ ಹೇಳುವ ನಿರೂಪಣೆ." },
  { word: "ಕನಸು", meaningKn: "ನಿದ್ರೆಯಲ್ಲಿ ಮನಸ್ಸಿಗೆ ಕಾಣುವ ದೃಶ್ಯ ಅಥವಾ ಅನುಭವ." },
  { word: "ನಗು", meaningKn: "ಸಂತೋಷವನ್ನು ಮುಖ ಮತ್ತು ಧ್ವನಿಯಿಂದ ತೋರಿಸುವ ಕ್ರಿಯೆ." },
  { word: "ಪ್ರೀತಿ", meaningKn: "ಯಾರಿಗಾದರೂ ಅಥವಾ ಯಾವುದಕ್ಕಾದರೂ ಇರುವ ಆಳವಾದ ಒಲವು." },
] as const;

/** Original, plain-English counterparts; avoids unreliable first-sense homonyms in Alar. */
export const WORD_GAME_MEANINGS_EN = {
  ಹೂವು: "The colourful part of a plant that blossoms.",
  ಪುಸ್ತಕ: "A written or printed work made of pages for reading.",
  ಸೂರ್ಯ: "The star that gives Earth light and heat.",
  ಚಂದ್ರ: "Earth's natural satellite, seen in the night sky.",
  ನಕ್ಷತ್ರ: "A distant heavenly body that shines in the night sky.",
  ಆಕಾಶ: "The wide open space seen above us.",
  ಮಳೆ: "Water that falls in drops from clouds.",
  ಗಾಳಿ: "The air around us that we breathe.",
  ಬೆಂಕಿ: "Flames that give light and heat while something burns.",
  ಸಮುದ್ರ: "A very large body of salt water.",
  ನದಿ: "A natural stream of water flowing along a course.",
  ಬೆಟ್ಟ: "Land that rises above the area around it.",
  ಮರ: "A large plant with a trunk, branches, and leaves.",
  ಗಿಡ: "A plant that is generally smaller than a tree.",
  ಹಣ್ಣು: "The edible part that grows on a plant after a flower.",
  ತರಕಾರಿ: "An edible part of a plant used in cooking.",
  ಬೆಳ್ಳುಳ್ಳಿ: "A white bulb used to add flavour to food.",
  ಈರುಳ್ಳಿ: "A layered bulb commonly used in cooking.",
  ನಾಯಿ: "A familiar animal often kept as a companion.",
  ಬೆಕ್ಕು: "A small, soft-furred animal often kept at home.",
  ಆಕಳು: "A large domestic animal kept for milk.",
  ಕುದುರೆ: "An animal used for riding and carrying loads.",
  ಹಕ್ಕಿ: "An animal with feathers and wings that can usually fly.",
  ಹಾವು: "A long animal without legs that moves along the ground.",
  ಇಲಿ: "A small animal with a long tail.",
  ಮೊಟ್ಟೆ: "A shelled object in which a young bird or similar animal develops.",
  ಬಾಗಿಲು: "The part that opens to let people enter or leave.",
  ಕಿಟಕಿ: "An opening in a wall that lets in light and air.",
  ಕುರ್ಚಿ: "A seat made for one person.",
  ಮೇಜು: "A piece of furniture with a flat top for placing things.",
  ದೀಪ: "A device used to provide light.",
  ಕನ್ನಡಿ: "A smooth surface that shows a reflection.",
  ಗಡಿಯಾರ: "A device that shows the time.",
  ಬಟ್ಟೆ: "Woven material used for wearing or sewing.",
  ಕಾಗದ: "A thin sheet used for writing, printing, or drawing.",
  ಬಣ್ಣ: "A quality such as red or blue that we see in an object.",
  ಚಿತ್ರ: "A drawn, painted, or photographed representation.",
  ಊಟ: "Food eaten as a meal, or the act of eating it.",
  ಅನ್ನ: "A staple food made by cooking rice.",
  ರೊಟ್ಟಿ: "A flat food made by shaping and cooking flour dough.",
  ಹಣ: "A medium used to buy goods or services.",
  ಅಂಗಡಿ: "A place where goods are sold.",
  ರಸ್ತೆ: "A path used by people and vehicles for travel.",
  ಬಸ್ಸು: "A large road vehicle that carries many passengers.",
  ರೈಲು: "A vehicle of connected coaches that travels on rails.",
  ಆಸ್ಪತ್ರೆ: "A place where sick or injured people receive treatment.",
  ಔಷಧ: "Medicine used to prevent or treat illness.",
  ಶಾಲೆ: "A place where students go to learn.",
  ಶಿಕ್ಷಕ: "A person who teaches students.",
  ವಿದ್ಯಾರ್ಥಿ: "A person who studies or learns.",
  ಅಪ್ಪ: "A familiar word used for one's father.",
  ಅಮ್ಮ: "A familiar word used for one's mother.",
  ಅಕ್ಕ: "An older sister.",
  ಅಣ್ಣ: "An older brother.",
  ತಂಗಿ: "A younger sister.",
  ತಮ್ಮ: "A younger brother.",
  ಮಗು: "A young child or baby.",
  ಗೆಳೆಯ: "A friend who shares affection and trust.",
  ಹೆಸರು: "A word used to identify a person, place, or thing.",
  ದೇಶ: "A territory with its own government and borders.",
  ರಾತ್ರಿ: "The dark period after sunset.",
  ದಿನ: "The time from morning to night, or a period of twenty-four hours.",
  ವಾರ: "A period of seven days.",
  ತಿಂಗಳು: "One of the twelve main divisions of a year.",
  ವರ್ಷ: "A period of twelve months.",
  ಸಮಯ: "The point or period when something happens.",
  ಹಬ್ಬ: "A special day celebrated with happiness.",
  ಆಟ: "An activity played for fun, exercise, or competition.",
  ಕೆಲಸ: "A task to be done or a person's occupation.",
  ಸಂಗೀತ: "The art of arranging sounds with melody and rhythm.",
  ಹಾಡು: "Words sung with a tune and rhythm.",
  ಕಥೆ: "An account of events told in sequence.",
  ಕನಸು: "Images or experiences that appear in the mind during sleep.",
  ನಗು: "The act of showing happiness through the face and voice.",
  ಪ್ರೀತಿ: "A deep feeling of affection for someone or something.",
} as const satisfies Record<(typeof WORD_GAME_ANSWERS)[number]["word"], string>;
