/** Additional familiar answers, with original CC BY-SA 4.0 bilingual explanations. */
export const EXTRA_WORD_GAME_ANSWERS = [
  { word: "ಉದ್ಯಾನ", meaningKn: "ಮರ, ಗಿಡ ಮತ್ತು ಹೂಗಳನ್ನು ಬೆಳೆಸಿ ಜನರಿಗಾಗಿ ಸಿದ್ಧಪಡಿಸಿದ ಸ್ಥಳ.", meaningEn: "A public or private place arranged with trees, plants, and flowers." },
  { word: "ಬೆಳಗ್ಗೆ", meaningKn: "ಸೂರ್ಯೋದಯದ ಸುತ್ತಲಿನ ದಿನದ ಮೊದಲ ಭಾಗ.", meaningEn: "The first part of the day, around sunrise." },
  { word: "ಸಂಜೆ", meaningKn: "ದಿನ ಮುಗಿದು ರಾತ್ರಿ ಆರಂಭವಾಗುವ ಸಮಯ.", meaningEn: "The time when day ends and night begins." },
  { word: "ಮಧ್ಯಾಹ್ನ", meaningKn: "ಬೆಳಗ್ಗೆ ಮತ್ತು ಸಂಜೆ ನಡುವಿನ ದಿನದ ಮಧ್ಯಭಾಗ.", meaningEn: "The middle of the day, between morning and evening." },
  { word: "ದೂರವಾಣಿ", meaningKn: "ದೂರದಲ್ಲಿರುವವರೊಂದಿಗೆ ಮಾತನಾಡಲು ಬಳಸುವ ಸಾಧನ.", meaningEn: "A device used to speak with someone far away." },
  { word: "ನಗರ", meaningKn: "ಹಳ್ಳಿಗಿಂತ ದೊಡ್ಡದಾದ ಜನವಸತಿ ಪ್ರದೇಶ.", meaningEn: "A populated place larger than a village." },
  { word: "ಹಳ್ಳಿ", meaningKn: "ನಗರಕ್ಕಿಂತ ಚಿಕ್ಕದಾದ ಗ್ರಾಮೀಣ ಜನವಸತಿ.", meaningEn: "A small settlement in a rural area." },
  { word: "ಪಟ್ಟಣ", meaningKn: "ಹಳ್ಳಿಗಿಂತ ದೊಡ್ಡದು, ನಗರಕ್ಕಿಂತ ಚಿಕ್ಕದಾದ ಜನವಸತಿ.", meaningEn: "A settlement generally larger than a village and smaller than a city." },
  { word: "ರಾಜಧಾನಿ", meaningKn: "ಒಂದು ರಾಜ್ಯ ಅಥವಾ ದೇಶದ ಆಡಳಿತ ಕೇಂದ್ರವಾದ ನಗರ.", meaningEn: "The city where a state or country's government is based." },
  { word: "ವಿಮಾನ", meaningKn: "ಆಕಾಶದಲ್ಲಿ ಹಾರುವ ಪ್ರಯಾಣ ವಾಹನ.", meaningEn: "A vehicle that carries people or goods through the air." },
  { word: "ವಾಹನ", meaningKn: "ಜನರು ಅಥವಾ ವಸ್ತುಗಳನ್ನು ಸಾಗಿಸುವ ಸಾಧನ.", meaningEn: "Something used to transport people or goods." },
  { word: "ಸೈಕಲ್ಲು", meaningKn: "ಎರಡು ಚಕ್ರಗಳನ್ನು ಕಾಲಿನಿಂದ ತುಳಿದು ಓಡಿಸುವ ವಾಹನ.", meaningEn: "A two-wheeled vehicle moved by pedalling." },
  { word: "ದೋಣಿ", meaningKn: "ನೀರಿನ ಮೇಲೆ ಸಾಗುವ ಚಿಕ್ಕ ವಾಹನ.", meaningEn: "A small vessel used to travel on water." },
  { word: "ಹಡಗು", meaningKn: "ಸಮುದ್ರದಲ್ಲಿ ಜನರು ಅಥವಾ ಸರಕು ಸಾಗಿಸುವ ದೊಡ್ಡ ನೌಕೆ.", meaningEn: "A large vessel that carries people or goods over water." },
  { word: "ಉದ್ಯೋಗ", meaningKn: "ಆದಾಯಕ್ಕಾಗಿ ಮಾಡುವ ನಿಯಮಿತ ಕೆಲಸ.", meaningEn: "Regular work done to earn an income." },
  { word: "ವ್ಯವಸಾಯ", meaningKn: "ಬೆಳೆ ಬೆಳೆಯುವ ಮತ್ತು ಕೃಷಿ ಮಾಡುವ ಕೆಲಸ.", meaningEn: "The work of cultivating land and growing crops." },
  { word: "ರೈತ", meaningKn: "ಹೊಲದಲ್ಲಿ ಬೆಳೆ ಬೆಳೆಸುವ ವ್ಯಕ್ತಿ.", meaningEn: "A person who grows crops on a farm." },
  { word: "ಕೃಷಿಕ", meaningKn: "ಕೃಷಿಯನ್ನು ವೃತ್ತಿಯಾಗಿ ಮಾಡುವ ವ್ಯಕ್ತಿ.", meaningEn: "A person whose occupation is farming." },
  { word: "ಮಾರುಕಟ್ಟೆ", meaningKn: "ವಸ್ತುಗಳನ್ನು ಕೊಳ್ಳುವ ಮತ್ತು ಮಾರುವ ಸ್ಥಳ.", meaningEn: "A place where goods are bought and sold." },
  { word: "ಕ್ರೀಡಾಂಗಣ", meaningKn: "ಕ್ರೀಡೆಗಳನ್ನು ಆಡಲು ಮತ್ತು ನೋಡಲು ಸಿದ್ಧಪಡಿಸಿದ ಸ್ಥಳ.", meaningEn: "A place prepared for playing and watching sports." },
  { word: "ಆಟಗಾರ", meaningKn: "ಆಟ ಅಥವಾ ಕ್ರೀಡೆಯಲ್ಲಿ ಭಾಗವಹಿಸುವ ವ್ಯಕ್ತಿ.", meaningEn: "A person who takes part in a game or sport." },
  { word: "ವಿಜಯ", meaningKn: "ಸ್ಪರ್ಧೆ ಅಥವಾ ಪ್ರಯತ್ನದಲ್ಲಿ ದೊರೆಯುವ ಗೆಲುವು.", meaningEn: "Success or a win in a contest or effort." },
  { word: "ಪರಾಜಯ", meaningKn: "ಸ್ಪರ್ಧೆ ಅಥವಾ ಪ್ರಯತ್ನದಲ್ಲಿ ಉಂಟಾಗುವ ಸೋಲು.", meaningEn: "A loss or defeat in a contest or effort." },
  { word: "ನೆರೆಹೊರೆ", meaningKn: "ನಮ್ಮ ಮನೆಗೆ ಹತ್ತಿರದ ಸ್ಥಳ ಮತ್ತು ಅಲ್ಲಿನ ಜನರು.", meaningEn: "The nearby area and the people who live there." },
  { word: "ಸಮಾಜ", meaningKn: "ಒಟ್ಟಾಗಿ ಬದುಕುವ ಜನರ ಸಮುದಾಯ.", meaningEn: "A community of people living together." },
  { word: "ಸಂಸ್ಕೃತಿ", meaningKn: "ಒಂದು ಸಮುದಾಯದ ಬದುಕು, ಕಲೆ, ನಂಬಿಕೆ ಮತ್ತು ಆಚರಣೆಗಳು.", meaningEn: "A community's way of life, arts, beliefs, and customs." },
  { word: "ಇತಿಹಾಸ", meaningKn: "ಹಿಂದೆ ನಡೆದ ಘಟನೆಗಳ ದಾಖಲೆಯೂ ಅಧ್ಯಯನವೂ.", meaningEn: "The record and study of events that happened in the past." },
  { word: "ಭೂಗೋಳ", meaningKn: "ಭೂಮಿ, ಸ್ಥಳಗಳು ಮತ್ತು ಪರಿಸರವನ್ನು ಅಧ್ಯಯನ ಮಾಡುವ ವಿಷಯ.", meaningEn: "The study of Earth, places, and environments." },
  { word: "ಗಣಿತ", meaningKn: "ಸಂಖ್ಯೆ, ಆಕಾರ ಮತ್ತು ಅಳತೆಯನ್ನು ಅಧ್ಯಯನ ಮಾಡುವ ವಿಷಯ.", meaningEn: "The study of numbers, shapes, and measurement." },
  { word: "ಶಿಕ್ಷಣ", meaningKn: "ಜ್ಞಾನ ಮತ್ತು ಕೌಶಲಗಳನ್ನು ಕಲಿಯುವ ಪ್ರಕ್ರಿಯೆ.", meaningEn: "The process of gaining knowledge and skills." },
  { word: "ಪರೀಕ್ಷೆ", meaningKn: "ಕಲಿತದ್ದನ್ನು ಅಥವಾ ಸಾಮರ್ಥ್ಯವನ್ನು ತಿಳಿಯುವ ಮೌಲ್ಯಮಾಪನ.", meaningEn: "An assessment of learning or ability." },
  { word: "ಫಲಿತಾಂಶ", meaningKn: "ಒಂದು ಕೆಲಸ, ಪರೀಕ್ಷೆ ಅಥವಾ ಘಟನೆಯ ಕೊನೆಯ ಪರಿಣಾಮ.", meaningEn: "The final result of an action, test, or event." },
  { word: "ರಜೆ", meaningKn: "ಶಾಲೆ ಅಥವಾ ಕೆಲಸದಿಂದ ಬಿಡುವಿರುವ ದಿನ ಅಥವಾ ಸಮಯ.", meaningEn: "Time away from school or work." },
  { word: "ಬೆಳಕು", meaningKn: "ವಸ್ತುಗಳನ್ನು ನೋಡಲು ನೆರವಾಗುವ ಪ್ರಕಾಶ.", meaningEn: "Brightness that allows things to be seen." },
  { word: "ಕತ್ತಲೆ", meaningKn: "ಬೆಳಕು ಇಲ್ಲದ ಅಥವಾ ಬಹಳ ಕಡಿಮೆ ಇರುವ ಸ್ಥಿತಿ.", meaningEn: "A state with no light or very little light." },
  { word: "ನೆರಳು", meaningKn: "ಬೆಳಕಿಗೆ ಅಡ್ಡಿಯಾದಾಗ ಬೀಳುವ ಕತ್ತಲಾದ ಆಕಾರ.", meaningEn: "A dark shape formed when something blocks light." },
  { word: "ಬಿಸಿಲು", meaningKn: "ಸೂರ್ಯನಿಂದ ನೇರವಾಗಿ ಬರುವ ಬೆಳಕು ಮತ್ತು ಬಿಸಿ.", meaningEn: "Direct light and heat from the sun." },
  { word: "ಚಳಿಗಾಲ", meaningKn: "ವರ್ಷದಲ್ಲಿ ಹವಾಮಾನ ಹೆಚ್ಚು ತಂಪಾಗಿರುವ ಕಾಲ.", meaningEn: "The colder season of the year." },
  { word: "ಬೇಸಿಗೆ", meaningKn: "ವರ್ಷದಲ್ಲಿ ಹವಾಮಾನ ಹೆಚ್ಚು ಬಿಸಿಯಾಗಿರುವ ಕಾಲ.", meaningEn: "The hotter season of the year." },
  { word: "ವಸಂತ", meaningKn: "ಚಳಿಗಾಲದ ಬಳಿಕ ಬರುವ ಹೂವು ಮತ್ತು ಹೊಸ ಎಲೆಗಳ ಕಾಲ.", meaningEn: "The season after winter when new leaves and flowers appear." },
  { word: "ಭೂಮಿ", meaningKn: "ನಾವು ವಾಸಿಸುವ ಗ್ರಹ ಅಥವಾ ನೆಲ.", meaningEn: "The planet we live on, or the ground beneath us." },
  { word: "ಕಾಡು", meaningKn: "ಬಹಳಷ್ಟು ಮರಗಳು ಮತ್ತು ಕಾಡುಜೀವಿಗಳಿರುವ ಪ್ರದೇಶ.", meaningEn: "An area with many trees and wild animals." },
  { word: "ಪ್ರಾಣಿ", meaningKn: "ಆಹಾರ ಸೇವಿಸಿ ಸ್ವತಃ ಚಲಿಸಬಲ್ಲ ಒಂದು ಜೀವಿ.", meaningEn: "A living creature that feeds and can move by itself." },
  { word: "ಜೀವಿ", meaningKn: "ಜೀವ ಹೊಂದಿರುವ ಸಸ್ಯ, ಪ್ರಾಣಿ ಅಥವಾ ಬೇರೆ ಅಸ್ತಿತ್ವ.", meaningEn: "A plant, animal, or other living being." },
  { word: "ಮನುಷ್ಯ", meaningKn: "ವಿಚಾರ, ಭಾಷೆ ಮತ್ತು ಸಮಾಜಜೀವನ ಹೊಂದಿರುವ ಮಾನವ ಜೀವಿ.", meaningEn: "A human being capable of thought, language, and social life." },
] as const;
